# Generated by Django 4.0.4 on 2022-06-21 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='organizations',
            new_name='organization',
        ),
    ]
