# Generated by Django 4.0.4 on 2022-06-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_organizations_job_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
