# Generated by Django 4.0.4 on 2022-07-03 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobseekers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='address',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='name',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='training',
            field=models.TextField(blank=True, null=True),
        ),
    ]
