# Generated by Django 4.0.4 on 2022-06-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Education', 'Education'), ('IT', 'IT'), ('Consultancy', 'Consultancy'), ('NGO/INGO', 'NGO/INGO'), ('Other', 'Other')], max_length=100)),
                ('details', models.TextField()),
                ('logo', models.ImageField(upload_to='organizations')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
