# Generated by Django 4.0.4 on 2022-06-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
