# Generated by Django 4.0.4 on 2022-07-03 03:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_alter_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
